definitions:
  env_versions: &env_versions
    xcode: 14.1
  triggering:
    push: &push_event
      events:
        - push
  scripts:
    - &installScripts
      name: Installing Scripts
      script: ./scripts/setup
    - &build
      name: Building Project 
      script: xcodebuild build -project "Wikipedia.xcodeproj" -scheme "Wikipedia" -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 13,OS=16.1' -configuration Debug CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO CODE_SIGNING_ALLOWED=NO 
    - &runTests
      name: Running Tests
      script: xcodebuild build -project "Wikipedia.xcodeproj" -scheme "Wikipedia" -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 13,OS=16.1' test
      test_report: build/ios/test/*.xml  
workflows:
  ios-mac-pro-workflow:
    name: iOS Mac Pro Workflow
    instance_type: mac_pro
    environment:
      <<: *env_versions
    triggering:
      <<: *push_event
    scripts:
      - *installScripts
      - *build
      - *runTests
  ios-m1-mac-mini-workflow:
    name: iOS M1 Mac Mini Workflow
    instance_type: mac_mini_m1
    environment:
      <<: *env_versions
    triggering:
      <<: *push_event
    scripts:
      - *installScripts
      - *build
      - *runTests
