definitions:
  env_versions: &env_versions
    vars:
      XCODE_PROJECT: "Wikipedia.xcodeproj"
      XCODE_SCHEME: "Wikipedia"
  scripts:
    - &installScripts
      name: Installing Scripts
      script: ./scripts/setup
    - &build
      name: Building Project 
      script: |
        time xcodebuild build \
          -project "$XCODE_PROJECT" \
          -scheme "$XCODE_SCHEME" \
          -sdk iphonesimulator \
          -configuration Debug \
          CODE_SIGN_IDENTITY="" \
          CODE_SIGNING_REQUIRED=NO \
          CODE_SIGNING_ALLOWED=NO
          # | xcpretty && exit ${PIPESTATUS[0]}
    - &runTests
      name: Run iOS UI and Unit tests
      script: |
        time xcodebuild build \
          -project "Wikipedia.xcodeproj" \
          -scheme "Wikipedia" \
          -sdk iphonesimulator \
          -destination 'platform=iOS Simulator,name=iPhone 14,OS=16.1' \
          test
    - &runTestsPretty
      name: Run iOS UI and Unit tests
      script: |
        time xcode-project run-tests \
          --project "$XCODE_PROJECT" \
          --scheme "$XCODE_SCHEME" \
          --device "iPhone 14"
workflows:
  ios:
    instance_type: mac_mini_m1
    environment:
      <<: *env_versions
    scripts:
      - *installScripts
      - *build
      - *runTests
