definitions:
  env_versions: &env_versions
    vars:
      XCODE_PROJECT: "Wikipedia.xcodeproj"
      XCODE_SCHEME: "Wikipedia"
  scripts:
    - &installScripts
      name: Installing Scripts
      script: ./scripts/setup
    - &build
      name: Building Project 
      script: |
        xcodebuild build \
          -project "$XCODE_PROJECT" \
          -scheme "$XCODE_SCHEME" \
          -sdk iphonesimulator \
          -configuration Debug \
          CODE_SIGN_IDENTITY="" \
          CODE_SIGNING_REQUIRED=NO \
          CODE_SIGNING_ALLOWED=NO | xcpretty && exit ${PIPESTATUS[0]}
    - &runTests
      name: Run iOS UI and Unit tests
      script: |
        xcode-project run-tests \
          --project "$XCODE_PROJECT" \
          --scheme "$XCODE_SCHEME" \
          --device "iPhone 14"
workflows:
  ios:
    instance_type: mac_mini_m1
    environment:
      <<: *env_versions
    scripts:
      - *installScripts
      - *build
